baseURL = "https://bryangilbert.com"
languageCode = "en-us"
title = "Bryan Gilbert's Blog"
theme = "academic"
copyright = "&copy; 2017 Bryan Gilbert"

disqusShortname = "bryangilbertsblog"
googleAnalytics = "UA-42597902-1"

enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
  name = "Bryan Gilbert"
  email = "contact@bryan.sh"
  avatar = "me.jpg"

  date_format = "Mon, Jan 2, 2006"


  ################
  # Highlighting #
  ################

  highlight = true
  highlight_languages = ["python", "lisp", "clojure", "scala", "java", "rust"]
  highlight_style = "zenburn"

  custom_css = ["custom.css"]
  # custom_js  = []


  ##########
  # Social #
  ##########

  sharing = true

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:contact@bryan.sh"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/gilbertw1"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//linkedin.com/in/gilbertw1/"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/bryangilbert"


[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "About"
  url = "#about"
  weight = 5

[taxonomies]
  tag = "tags"
  category = "categories"
