baseURL = "//bryangilbert.com/"
languageCode = "en-us"
title = "Bryan Gilbert's Blog"
theme = "hugo-icarus-theme"

disqusShortname = "bryangilbertsblog"
googleAnalytics = "UA-42597902-1"

paginate = 10
footnotereturnlinkcontents = "↩"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
  author = "Bryan Gilbert"
  bio = "Programmer that enjoys working on tough problems and learning new technologies."
  location = "Charleston, SC"
  email = "bryan@bryan.sh"
  avatar = "/img/me.jpg"
  copyright = "Bryan Gilbert"
  date_format = "2006-01-02"
  mainSections = ["post"]

  custom_css = ["/css/custom.css", "/css/github.css"]
  custom_js  = ["/js/custom.js", "//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/languages/scala.min.js"]
  
  ################
  # Highlighting #
  ################

  highlight = true
  highlight_languages = ["python", "lisp", "clojure", "scala", "java", "rust"]
  highlight_style = "zenburn"


[params.profile]
    follow_button = "https://github.com/gilbertw1"

  ##########
  # Social #
  ##########

[social]

  github = "gilbertw1"
  linkedin = "gilbertw1"
  reddit = "gilbertw1"
  twitter = "bryangilbert"
  googleplus = "+BryanGilbert"


[params.widgets]
    recent_articles = true
    categories = true
    tags = true


[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"
